import type {Metadata} from "next"
import {Inter, Montserrat_Alternates} from "next/font/google"
import {ReactNode} from "react"
import {Providers} from "@/app/providers"
import "./globals.scss"

const inter = Inter({subsets: ["latin"]})
const montserrat = Montserrat_Alternates({
    subsets: ["cyrillic", "latin", "vietnamese", "cyrillic-ext", "latin-ext"],
    weight: ["500", "600", "700"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={montserrat.className}>
        <Providers>{children}</Providers>
        </body>
        </html>
    )
}
